{% set python_min = "3.11.0" %}
{% set name = "spiderweb-framework" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spiderweb_framework-{{ version }}.tar.gz
  sha256: 5c84e98537eb26d864892c97809117f850b2cb7eae95db7ba38767ddfc0e412f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - advanced-alchemy >=1.6.3,<2.0.0
    - cryptography >=46.0.2
    - email-validator >=2.3.0
    - jinja2 >=3.1.6
    - multipart >=1.3.0
    - sqlalchemy >=2.0.44

test:
  imports:
    - spiderweb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/itsthejoker/spiderweb
  doc_url: https://itsthejoker.github.io/spiderweb/
  summary: A small web framework, just big enough for a spider.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
