{% set python_min = "3.11.0" %}
{% set name = "spiderweb-framework" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spiderweb_framework-{{ version }}.tar.gz
  sha256: aa894fbb50e10d25d311d5da99cbd9a98fc7643cf216aed5a20c0b6248a7cb5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core <2
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - peewee >=3.17.6,<4.0.0
    - jinja2 >=3.1.4,<4.0.0
    - cryptography >=43.0.0,<44.0.0
    - email-validator >=2.2.0,<3.0.0
    - pydantic >=2.8.2,<3.0.0

test:
  imports:
    - spiderweb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/itsthejoker/spiderweb
  doc_url: https://itsthejoker.github.io/spiderweb/
  summary: A small web framework, just big enough for a spider.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
